### ISSUE TITLE
Port code from development project

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/NeuroLinker#1]
# Description
Port code from the development project over to NeuroLinker.

# Tasks
- [x] Port code over
- [x] Test code to see if port was successful
- [x] Code NineTailLabs ReSharper codecleanup and codemaid config
