### ISSUE TITLE
Set up build

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/NeuroLinker#2]
# Description
Grab a copy of the VaraniumSharp build script and adjust it for NeuroLinker. Once that is completed set up all the services required and prepare for the first build

# Tasks
- [x] Copy and configure build script
- [x] Set up AppVeyor
- [x] Set up CodeFactor
- [x] Set up CodeCover
- [x] Set up documentation server
