### ISSUE TITLE
Update to .NetStandard 2.0

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/NeuroLinker#43]
# Description
No longer have a need to keep the library as a full framework library, convert to .NetStandard and embrace the future.

# Tasks
- [x] Convert to .NetStandard2.0
- [x] Fix unit testing in Cake script
- [x] Figure out how to get hold of the test result file (See [here](https://github.com/spekt/nunit.testlogger))
- [x] Clean up and move AltCover script to CakeScripts (Check if there is actually a way to combine coverage reports or to simply run test on sln level)
- [x] Fix broken unit test
- [x] Hook up Semver for versioning
- [x] Fix nuspec file
